### ISSUE TITLE
Confusing prerequisites on “TUTORIAL: How to Create an æternity Account With CLI?” 

### ISSUE THREAD

**Issue by moritzfelipe** [aeternity/tutorials#13]
Great tutorial, however, I came across some problems, I will address them in separate issues.

Under prerequisites, you write: “_Installed node and npm (see the other tutorials to learn how to run a node and npm)”_. It is not totally clear to me if you mean that I need to have installed nodejs or to have up a running node since that's what you referencing to in the parentheses.

**Comment by VladislavIvanov** [comment]
Thank you for the comment @moritzfelipe ! The right prerequisite condition is ```Installed node.js and npm (node package manager)```. This issue will close once PR#16 is merged to master.
