### ISSUE TITLE
Wrong tutorial overview for "Deploying Sophia smart contracts with init parameters"

### ISSUE THREAD

**Issue by sadiqevani** [aeternity/tutorials#17]
The tutorial overview for the following tutorial is wrong, and is not about: Deploying Sophia smart contracts with init parameters

https://github.com/aeternity/tutorials/blob/master/deploy-with-init-params.md#tutorial-overview

**Comment by thepiwo** [comment]
thanks for letting us know @sadiqevani

**Comment by Perseverance** [comment]
Fixed here https://github.com/aeternity/tutorials/commit/274ffc8cac9459485ba6072bf96b646552c9c52a
