### ISSUE TITLE
Got this error when running forgae node

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [aeternity/tutorials#36]
C:\Users\goote_000\Documents\smart_contracts\new_aepps\voting_app>forgae node
error: 'Error: Command failed: docker   ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers
/json: open //./pipe/docker_engine: The system cannot find the file specified. I
n the default daemon configuration on Windows, the docker client must be run ele
vated to connect. This error may also indicate that the docker daemon is not run
ning.
' stdout = '' stderr = 'error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker
_engine/v1.39/containers/json: open //./pipe/docker_engine: The system cannot fi
nd the file specified. In the default daemon configuration on Windows, the docke
r client must be run elevated to connect. This error may also indicate that the
docker daemon is not running.
'

**Comment by thepiwo** [comment]
there is a pre-requisite to have docker installed on your system, is this true for your configuration?

**Comment by GoodnessEzeokafor** [comment]
ok i did nw i have this
error: 'Error: Command failed: docker   ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json: open //./pipe/docker_engine: The
system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run ele
vated to connect. This error may also indicate that the docker daemon is not running.
' stdout = '' stderr = 'error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json: open //./
pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docke
r client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by GoodnessEzeokafor** [comment]
when i run docker ps on my commandline i get this
C:\Users\goote_000\Documents\smart_contracts\new_aepps\voting_app>docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED
STATUS              PORTS               NAMES

**Comment by GoodnessEzeokafor** [comment]
but forgae node still gives
C:\Users\goote_000\Documents\smart_contracts\new_aepps\voting_app>forgae node
error: 'Error: Command failed: <h6>docker   ps </h6>
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers
/json: open //./pipe/docker_engine: The system cannot find the file specified. I
n the default daemon configuration on Windows, the docker client must be run ele
vated to connect. This error may also indicate that the docker daemon is not run
ning.
' stdout = '' stderr = 'error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker
_engine/v1.39/containers/json: open //./pipe/docker_engine: The system cannot fi
nd the file specified. In the default daemon configuration on Windows, the docke
r client must be run elevated to connect. This error may also indicate that the
docker daemon is not running.
'

**Comment by GoodnessEzeokafor** [comment]
any idea?????
i'm using windows 8.1

**Comment by thepiwo** [comment]
did you restart your pc? `docker daemon is not running` is not a issue related to forgae but docker problem in general

**Comment by GoodnessEzeokafor** [comment]
i did and my docker is working

**Comment by GoodnessEzeokafor** [comment]
also got this err when i ran forgae compile
C:\Users\goote_000\Documents\smart_contracts\new_aepps\voting_app>forgae compile

===== Compiling contracts =====
API ERROR: Error: connect ECONNREFUSED 127.0.0.1:3001

What am i missing???

**Comment by thepiwo** [comment]
@maptuhec @alekseytsekov can you help here?

**Comment by GoodnessEzeokafor** [comment]
i was using docker toolbox
