### ISSUE TITLE
Compile Failed on tuttorial deploy-with-init-params

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [aeternity/tutorials#43]
goote_000@HP MINGW64 ~/Documents/smart_contracts/voting_app
$ forgae compile
===== Compiling contracts =====
API ERROR: Error: connect ECONNREFUSED 127.0.0.1:3001

**Comment by thepiwo** [comment]
@maptuhec or @alekseytsekov can you have a look?

**Comment by alekseytsekov** [comment]
@thepiwo yes

**Comment by maptuhec** [comment]
@GoodnessEzeokafor running `forgae compile` uses the spawned local compiler, the error says that your local compiler is not running. You should start the compiler or provide a link to already running compiler like this : `forgae compile --compiler http://your-compiler.com`

Best Martin

**Comment by thepiwo** [comment]
@maptuhec could you also reference the documentation for this?

**Comment by maptuhec** [comment]
of course, here : https://forgae.gitbook.io/forgae/developer-documentation/forgae-cli/compile

**Comment by GoodnessEzeokafor** [comment]
could i get the gitbook link for your javascript sdk
thanks

**Comment by GoodnessEzeokafor** [comment]
C:\Users\goote_000\Documents\smart_contracts\new_aepps>node index.js
Error: Compiler not defined
    at Object.isInit (C:\Users\goote_000\Documents\smart_contracts\new_aepps\nod
e_modules\@aeternity\aepp-sdk\dist\aepp-sdk.js:1:129993)
    at Object.<anonymous> (C:\Users\goote_000\Documents\smart_contracts\new_aepp
s\node_modules\@aeternity\aepp-sdk\dist\aepp-sdk.js:1:127469)
    at u (C:\Users\goote_000\Documents\smart_contracts\new_aepps\node_modules\@a
eternity\aepp-sdk\dist\aepp-sdk.js:1:16341)
    at Generator._invoke (C:\Users\goote_000\Documents\smart_contracts\new_aepps
\node_modules\@aeternity\aepp-sdk\dist\aepp-sdk.js:1:16129)
    at Generator.t.(anonymous function) [as next] (C:\Users\goote_000\Documents\
smart_contracts\new_aepps\node_modules\@aeternity\aepp-sdk\dist\aepp-sdk.js:1:16
763)
    at n (C:\Users\goote_000\Documents\smart_contracts\new_aepps\node_modules\@a
eternity\aepp-sdk\dist\aepp-sdk.js:1:2050)
    at c (C:\Users\goote_000\Documents\smart_contracts\new_aepps\node_modules\@a
eternity\aepp-sdk\dist\aepp-sdk.js:1:2260)
    at C:\Users\goote_000\Documents\smart_contracts\new_aepps\node_modules\@aete
rnity\aepp-sdk\dist\aepp-sdk.js:1:2319
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\goote_000\Documents\smart_contracts\new_aepp
s\node_modules\@aeternity\aepp-sdk\dist\aepp-sdk.js:1:2201)
(node:6008) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'b
ytecode' of undefined
    at main (C:\Users\goote_000\Documents\smart_contracts\new_aepps\index.js:42:
48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 3)
(node:6008) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

i got this error when using u guys javascripts sdk for node js

**Comment by GoodnessEzeokafor** [comment]
#index.js
const fs = require('fs');
const {Universal} = require('@aeternity/aepp-sdk');

const config = {
    host:'https://sdk-testnet.aepps.com',
    gas:200000,
    ttl:55
}

// function to hold all our example code
const main = async(name) => {
    // insert all of the following here
    // function to log any errors
    const logError = (error) => console.error(error);

    //function to decode errors from contract calling
    const decodeError = async(error) => {
        //results from the node need to be decoded to be human readable
        const decodedError = await client.contractDecodeData('string', error.returnValue).catch(logError);
        console.error('error:', decodedError.value);
    };

    // initialize the aeternity sdk client
    const client = await Universal({
        url: 'https://sdk-testnet.aepps.com',
        internalUrl: 'https://sdk-testnet.aepps.com',
        keypair: {
            publicKey : 'ak_2mwRmUeYmfuW93ti9HMSUJzCk1EYcQEfikVSzgo6k2VghsWhgU',
            secretKey: 'bb9f0b01c8c9553cfbaf7ef81a50f977b1326801ebf7294d1c2cbccdedf27476e9bbf604e611b5460a3b3999e9771b6f60417d73ce7c5519e12f7e127a1225ca'
        },
        networkId: 'ae_uat',
        nativeMode:true
    });
    
    // read the ExampleContract.aes from same directory
    const contract = fs.readFileSync('./ExampleContract.aes', 'utf-8');

    // use the client to compile the contract code, catching eventual errors
    const compiled = await client.contractCompile(contract).catch(logError);

    // logging the bytecode output to the console to see the code work
    console.log('contract bytecode:', compiled.bytecode);


}

main();

**Comment by GoodnessEzeokafor** [comment]
#ExampleContract.aes
contract Bucketlist =
  record state = {
    index_counter : int,
    bucketlist : map(int, string),
    completed : map(int, bool) }
    
  public stateful entrypoint init() =
    { index_counter = 0,
      bucketlist = {},
      completed = {}}
  public entrypoint get_task_count() : int = 
    state.index_counter
  public stateful entrypoint add_new_bucketlist(_newbucketlist : string) : string =
    put(state{bucketlist[state.index_counter] = _newbucketlist })
    put(state{completed[state.index_counter] = false})
    put(state{index_counter = state.index_counter + 1})
    _newbucketlist
  
  public stateful entrypoint complete_bucketlist(_index : int) : bool =
    put(state{completed[_index] = true })
    true
  public entrypoint get_bucketlist_by_index(_index:int) : string =
    switch(Map.lookup(_index, state.bucketlist))
      None => ""
      Some(x) => x
      
  public entrypoint bucketlist_is_completed(_index : int) : bool =
    switch(Map.lookup(_index, state.completed))
      None => false
      Some(x) => x
      
  public entrypoint get_bucket_list_length() : int = 
    state.index_counter

**Comment by maptuhec** [comment]
@GoodnessEzeokafor here is a link to the JS-SDK: 
https://github.com/aeternity/aepp-sdk-js 
you can find the documentation there.

As far for the error, you haven't provided a link to a compiler in client.

``` client = await Universal({
            url: network.url,
            internalUrl,
            keypair: keypair,
            nativeMode: true,
            networkId: network.networkId,
            compilerUrl: network.compilerUrl
        })```

is the right configuration.

**Comment by GoodnessEzeokafor** [comment]
sorry been busy
i'll try this and get back to you guys

**Comment by thepiwo** [comment]
any update here? otherwise we can close this

**Comment by marc0olo** [comment]
cleaning up the repo now by making a new branch and updating most important tutorials. this issue won't be considered
