### ISSUE TITLE
No -n option for compiling

### ISSUE THREAD

**Issue by thepiwo** [aeternity/tutorials#51]
https://github.com/aeternity/tutorials/blob/master/build-to-do-list-aepp-1.md#compiling-the-contract

```
→ forgae compile -n testnet

error: unknown option `-n'
```

**Comment by thepiwo** [comment]
Additionally without `-n` it fails as compiler is not yet started

**Comment by marc0olo** [comment]
cleaning up the repo now by making a new branch and updating most important tutorials. this issue won't be considered
